{{- if and .Values.global.leangraph.enabled .Values.nginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: atlas-leangraph-nginx-service
  namespace: {{ .Values.Namespace }}
  labels:
    app: atlas-leangraph-nginx
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: atlas-leangraph-nginx
    release: {{ .Release.Name }}
{{- end }}

