{{- if and .Values.global.leangraph.enabled .Values.nginx.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas-leangraph-nginx
  namespace: {{ .Values.Namespace }}
  labels:
    app: atlas-leangraph-nginx
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    configmap.reloader.stakater.com/reload: "atlas-leangraph-nginx-config"
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      app: atlas-leangraph-nginx
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: atlas-leangraph-nginx
        release: {{ .Release.Name }}
    spec:
      {{- with .Values.atlas.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: nginx
          image: ghcr.io/atlanhq/nginx-vts-atlan-v2:1.27.5.1-multiarch
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-log-volume
              mountPath: /var/log/nginx
          livenessProbe:
            httpGet:
              path: /nginx_health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /nginx_health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      {{- if .Values.atlas.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml .Values.atlas.imagePullSecrets | nindent 8 }}
      {{- end }}
      volumes:
        - name: nginx-log-volume
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: atlas-leangraph-nginx-config
{{- end }}

