{{- if and .Values.nginx.enabled .Values.atlas.leangraph.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: atlas-nginx-mirror
  namespace: {{ .Values.Namespace }}
  labels:
    app: atlas-nginx-mirror
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: atlas-nginx-mirror
    release: {{ .Release.Name }}
{{- end }}

